[2025-09-29T00:07:52.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-29T00:07:52.906+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.train_model scheduled__2025-09-28T00:00:00+00:00 [queued]>
[2025-09-29T00:07:52.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.train_model scheduled__2025-09-28T00:00:00+00:00 [queued]>
[2025-09-29T00:07:52.910+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-29T00:07:52.914+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2025-09-28 00:00:00+00:00
[2025-09-29T00:07:52.919+0000] {standard_task_runner.py:64} INFO - Started process 92150 to run task
[2025-09-29T00:07:52.922+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'train_model', 'scheduled__2025-09-28T00:00:00+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmple1p_819']
[2025-09-29T00:07:52.924+0000] {standard_task_runner.py:91} INFO - Job 245: Subtask train_model
[2025-09-29T00:07:52.943+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.train_model scheduled__2025-09-28T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-09-29T00:07:52.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-28T00:00:00+00:00'
[2025-09-29T00:07:52.973+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-29T00:07:52.983+0000] {kudryakov_hw1-checkpoint.py:170} INFO - Начали обучение модели start-ts 2025-09-29T00:07:52.978393
[2025-09-29T00:07:52.987+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-29T00:07:52.990+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-29T00:07:58.861+0000] {kudryakov_hw1-checkpoint.py:187} INFO - Закончили обучение модели end-ts 2025-09-29T00:07:58.861499
[2025-09-29T00:07:59.742+0000] {kudryakov_hw1-checkpoint.py:202} INFO - Успешно загрузили модель
[2025-09-29T00:07:59.745+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-29T00:07:59.746+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-29T00:07:59.756+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=train_model, run_id=scheduled__2025-09-28T00:00:00+00:00, execution_date=20250928T000000, start_date=20250929T000752, end_date=20250929T000759
[2025-09-29T00:07:59.775+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-29T00:07:59.787+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-29T00:07:59.788+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
