[2025-10-03T00:00:18.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T00:00:18.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.train_model scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T00:00:18.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.train_model scheduled__2025-10-02T00:00:00+00:00 [queued]>
[2025-10-03T00:00:18.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T00:00:18.202+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2025-10-02 00:00:00+00:00
[2025-10-03T00:00:18.206+0000] {standard_task_runner.py:64} INFO - Started process 85911 to run task
[2025-10-03T00:00:18.208+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'train_model', 'scheduled__2025-10-02T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/kudryakov_hw1-checkpoint.py', '--cfg-path', '/tmp/tmpkk2a3lmp']
[2025-10-03T00:00:18.209+0000] {standard_task_runner.py:91} INFO - Job 269: Subtask train_model
[2025-10-03T00:00:18.229+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.train_model scheduled__2025-10-02T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-10-03T00:00:18.264+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-02T00:00:00+00:00'
[2025-10-03T00:00:18.265+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T00:00:18.275+0000] {kudryakov_hw1-checkpoint.py:170} INFO - Начали обучение модели start-ts 2025-10-03T00:00:18.270862
[2025-10-03T00:00:18.278+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-10-03T00:00:18.278+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-10-03T00:00:24.529+0000] {kudryakov_hw1-checkpoint.py:187} INFO - Закончили обучение модели end-ts 2025-10-03T00:00:24.529022
[2025-10-03T00:00:25.455+0000] {kudryakov_hw1-checkpoint.py:202} INFO - Успешно загрузили модель
[2025-10-03T00:00:25.456+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-03T00:00:25.457+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T00:00:25.461+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=train_model, run_id=scheduled__2025-10-02T00:00:00+00:00, execution_date=20251002T000000, start_date=20251003T000018, end_date=20251003T000025
[2025-10-03T00:00:25.477+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-03T00:00:25.489+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-03T00:00:25.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
