[2025-10-02T00:00:02.668+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-02T00:00:02.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-10-01T00:00:00+00:00 [queued]>
[2025-10-02T00:00:02.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-10-01T00:00:00+00:00 [queued]>
[2025-10-02T00:00:02.678+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-02T00:00:02.682+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-10-01 00:00:00+00:00
[2025-10-02T00:00:02.685+0000] {standard_task_runner.py:64} INFO - Started process 67188 to run task
[2025-10-02T00:00:02.702+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'scheduled__2025-10-01T00:00:00+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/kudryakov_hw1.py', '--cfg-path', '/tmp/tmpo6_qeaew']
[2025-10-02T00:00:02.705+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask collect_data
[2025-10-02T00:00:02.726+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data scheduled__2025-10-01T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-10-02T00:00:02.757+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-01T00:00:00+00:00'
[2025-10-02T00:00:02.757+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-02T00:00:02.767+0000] {kudryakov_hw1.py:78} INFO - Началась загрузка данных
[2025-10-02T00:00:02.790+0000] {kudryakov_hw1.py:85} INFO - Данные получили
[2025-10-02T00:00:02.797+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-10-02T00:00:02.797+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-10-02T00:00:04.125+0000] {kudryakov_hw1.py:94} INFO - Данные успешно загружены
[2025-10-02T00:00:04.127+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-02T00:00:04.128+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-02T00:00:04.137+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=collect_data, run_id=scheduled__2025-10-01T00:00:00+00:00, execution_date=20251001T000000, start_date=20251002T000002, end_date=20251002T000004
[2025-10-02T00:00:04.156+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-10-02T00:00:04.170+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-02T00:00:04.171+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
