[2025-09-25T18:45:50.142+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T18:45:50.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:40:29.055088+00:00 [queued]>
[2025-09-25T18:45:50.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:40:29.055088+00:00 [queued]>
[2025-09-25T18:45:50.152+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-09-25T18:45:50.157+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_model> on 2025-09-25 18:40:29.055088+00:00
[2025-09-25T18:45:50.161+0000] {standard_task_runner.py:64} INFO - Started process 56879 to run task
[2025-09-25T18:45:50.167+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_model', 'manual__2025-09-25T18:40:29.055088+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/kudryakov_hw1.py', '--cfg-path', '/tmp/tmpehrdf1_j']
[2025-09-25T18:45:50.172+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask collect_metrics_model
[2025-09-25T18:45:50.200+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:40:29.055088+00:00 [running]> on host 2b301b74205f
[2025-09-25T18:45:50.248+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T18:40:29.055088+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T18:40:29.055088+00:00'
[2025-09-25T18:45:50.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T18:45:50.255+0000] {logging_mixin.py:188} INFO - collect_metrics_model
[2025-09-25T18:45:50.255+0000] {kudryakov_hw1.py:197} INFO - Начали расчет метрик
[2025-09-25T18:45:50.260+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T18:45:50.261+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T18:45:53.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T18:45:53.645+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kudryakov_hw1.py", line 207, in collect_metrics_model
    metrics = {
NameError: name 'y_pred' is not defined
[2025-09-25T18:45:53.649+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hw1, task_id=collect_metrics_model, run_id=manual__2025-09-25T18:40:29.055088+00:00, execution_date=20250925T184029, start_date=20250925T184550, end_date=20250925T184553
[2025-09-25T18:45:53.655+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task collect_metrics_model (name 'y_pred' is not defined; 56879)
[2025-09-25T18:45:53.696+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T18:45:53.704+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T18:45:53.704+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
