[2025-09-25T18:42:23.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-25T18:42:23.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:42:05.883911+00:00 [queued]>
[2025-09-25T18:42:23.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:42:05.883911+00:00 [queued]>
[2025-09-25T18:42:23.381+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-25T18:42:23.386+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_metrics_model> on 2025-09-25 18:42:05.883911+00:00
[2025-09-25T18:42:23.391+0000] {standard_task_runner.py:64} INFO - Started process 56240 to run task
[2025-09-25T18:42:23.398+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_metrics_model', 'manual__2025-09-25T18:42:05.883911+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/kudryakov_hw1.py', '--cfg-path', '/tmp/tmpnrecw9wv']
[2025-09-25T18:42:23.402+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask collect_metrics_model
[2025-09-25T18:42:23.481+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_metrics_model manual__2025-09-25T18:42:05.883911+00:00 [running]> on host 2b301b74205f
[2025-09-25T18:42:23.597+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_metrics_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-25T18:42:05.883911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-25T18:42:05.883911+00:00'
[2025-09-25T18:42:23.598+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-25T18:42:23.607+0000] {logging_mixin.py:188} INFO - collect_metrics_model
[2025-09-25T18:42:23.608+0000] {kudryakov_hw1.py:194} INFO - Начали расчет метрик
[2025-09-25T18:42:23.613+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-25T18:42:23.613+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-25T18:42:26.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-25T18:42:26.802+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kudryakov_hw1.py", line 204, in collect_metrics_model
    "r_squared": float(r2_score(y_test, y_pred)),
NameError: name 'r2_score' is not defined
[2025-09-25T18:42:26.816+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=hw1, task_id=collect_metrics_model, run_id=manual__2025-09-25T18:42:05.883911+00:00, execution_date=20250925T184205, start_date=20250925T184223, end_date=20250925T184226
[2025-09-25T18:42:26.825+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task collect_metrics_model (name 'r2_score' is not defined; 56240)
[2025-09-25T18:42:26.862+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-25T18:42:26.875+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-25T18:42:26.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
