[2025-09-29T00:07:38.532+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-29T00:07:38.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-28T00:00:00+00:00 [queued]>
[2025-09-29T00:07:38.540+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw1.collect_data scheduled__2025-09-28T00:00:00+00:00 [queued]>
[2025-09-29T00:07:38.540+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-29T00:07:38.544+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): collect_data> on 2025-09-28 00:00:00+00:00
[2025-09-29T00:07:38.547+0000] {standard_task_runner.py:64} INFO - Started process 92109 to run task
[2025-09-29T00:07:38.549+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hw1', 'collect_data', 'scheduled__2025-09-28T00:00:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/kudryakov_hw1.py', '--cfg-path', '/tmp/tmp05c94xmd']
[2025-09-29T00:07:38.550+0000] {standard_task_runner.py:91} INFO - Job 243: Subtask collect_data
[2025-09-29T00:07:38.566+0000] {task_command.py:426} INFO - Running <TaskInstance: hw1.collect_data scheduled__2025-09-28T00:00:00+00:00 [running]> on host 2b301b74205f
[2025-09-29T00:07:38.602+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='VLADISLAV KUDRYAKOV' AIRFLOW_CTX_DAG_ID='hw1' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2025-09-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-28T00:00:00+00:00'
[2025-09-29T00:07:38.602+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-29T00:07:38.612+0000] {kudryakov_hw1.py:78} INFO - Началась загрузка данных
[2025-09-29T00:07:38.644+0000] {kudryakov_hw1.py:85} INFO - Данные получили
[2025-09-29T00:07:38.651+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2025-09-29T00:07:38.652+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2025-09-29T00:07:39.963+0000] {kudryakov_hw1.py:94} INFO - Данные успешно загружены
[2025-09-29T00:07:39.965+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-29T00:07:39.966+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-29T00:07:39.973+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hw1, task_id=collect_data, run_id=scheduled__2025-09-28T00:00:00+00:00, execution_date=20250928T000000, start_date=20250929T000738, end_date=20250929T000739
[2025-09-29T00:07:40.027+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-29T00:07:40.044+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-29T00:07:40.045+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
